"""Built-in offline fixtures."""

DEFAULT_MARKET = {
    "date": "2026-05-28",
    "total_volume_billion": 13260.0,
    "policy_score": 3.8,
    "sentiment_score": 3.4,
    "trend_score": 3.6,
    "advancers": 3128,
    "decliners": 1841,
    "hot_sectors": ["储能", "汽车零部件", "算力"],
    "cold_sectors": ["地产", "白酒"],
    "policy_highlights": ["设备更新政策延续", "出口链补库信号增强"],
    "leaders": ["宁德时代", "比亚迪", "中际旭创"],
    "overseas_signal": "偏多",
}

DEFAULT_STOCKS = [
    {
        "code": "300750",
        "name": "宁德时代",
        "sector": "储能",
        "price": 201.5,
        "ma20": 196.0,
        "boll_position": 0.68,
        "pe": 24.0,
        "q1_growth": 18.0,
        "turnover_million": 12800.0,
        "momentum_score": 4.4,
        "support": 193.0,
        "resistance": 216.0,
        "catalyst": "储能和海外订单持续改善",
        "notes": ["龙头辨识度高", "适合趋势跟随"],
    },
    {
        "code": "002594",
        "name": "比亚迪",
        "sector": "汽车",
        "price": 255.0,
        "ma20": 248.0,
        "boll_position": 0.64,
        "pe": 27.0,
        "q1_growth": 21.0,
        "turnover_million": 9600.0,
        "momentum_score": 4.2,
        "support": 246.0,
        "resistance": 270.0,
        "catalyst": "新车型销量和出海数据继续超预期",
        "notes": ["板块中军", "适合波段"],
    },
    {
        "code": "600519",
        "name": "贵州茅台",
        "sector": "白酒",
        "price": 1672.0,
        "ma20": 1688.0,
        "boll_position": 0.42,
        "pe": 29.0,
        "q1_growth": 9.0,
        "turnover_million": 3400.0,
        "momentum_score": 2.8,
        "support": 1650.0,
        "resistance": 1718.0,
        "catalyst": "估值回落后的防御性配置",
        "notes": ["防御属性强"],
    },
    {
        "code": "000001",
        "name": "平安银行",
        "sector": "银行",
        "price": 11.8,
        "ma20": 11.4,
        "boll_position": 0.57,
        "pe": 5.6,
        "q1_growth": 4.0,
        "turnover_million": 620.0,
        "momentum_score": 3.1,
        "support": 11.3,
        "resistance": 12.2,
        "catalyst": "高股息和估值修复逻辑稳定",
        "notes": ["低波动"],
    },
    {
        "code": "600290",
        "name": "*ST华仪",
        "sector": "电力设备",
        "price": 2.9,
        "ma20": 3.4,
        "boll_position": 0.18,
        "pe": 0.0,
        "q1_growth": -35.0,
        "turnover_million": 32.0,
        "momentum_score": 1.2,
        "support": 2.7,
        "resistance": 3.1,
        "catalyst": "",
        "under_investigation": True,
        "delisting_risk": True,
        "earnings_shock": True,
        "earnings_disclosed": False,
        "notes": ["高位解套需求大", "不符合主策略"],
    },
]
